name: Build Docs

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push OCIP docs
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        push: true
        build-args: |
          MKDOCS_CONFIG=mkdocs-ocip.yml
        tags: |
          ghcr.io/fourteen-ip/mercury-ocip-docs:latest

    - name: Build and push CLI docs
      uses: docker/build-push-action@v6.9.0
      with:
        context: .
        push: true
        build-args: |
          MKDOCS_CONFIG=mkdocs-cli.yml
        tags: |
          ghcr.io/fourteen-ip/mercury-cli-docs:latest
